<<<<<<< HEAD
# Generated by Django 2.2.8 on 2020-01-01 22:59
=======
# Generated by Django 2.2.8 on 2019-12-18 19:31
>>>>>>> 6dd2f503573253e3b68113ce2cacbe7a9b4bcd3b

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
